### ISSUE TITLE
Lack of perl installation throws misleading error message

### ISSUE THREAD

**Issue by minerharry** [RuleWorld/BNGTutorial#1]
When I ran the visualize command through the vscode extension, I kept getting a "FileNotFoundError: [WinError 2] The system cannot find the file specified" with no other context. Searching through the code, I found that the test_bngexec function was throwing the error when it tried to run from the command line, because I did not have a perl installation. It seems there is a util function defined just above it in utils.py specifically to check for perl, but it is never used in the source. Could you add a more descriptive error messages for windows users without a perl installation? Thanks

**Comment by ASinanSaglam** [comment]
Hi, 

Thank you for posting the issue. This is both related to extension https://github.com/RuleWorld/BNG_vscode_extension as well as the Python package https://github.com/RuleWorld/PyBioNetGen. 

We will soon release a version of the extension that does this check upon activation and will warn the user from the extension-end (with a pop-up window that also suggests the use of strawberry perl for windows users). The code is in as of today but we haven't made a release yet, should be released within the week. 

PyBNG will also have better error reporting before a full release, however, we probably won't explicitly check for perl every single time PyBNG runs. That is why the perl checking isn't actually used in the source code. 

Hope that addresses your issue. 

Best,

**Comment by minerharry** [comment]
Thanks!
